services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/all_puntos
    depends_on:
      - db

  db:
    image: postgis/postgis:16-3.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: all_puntos
    volumes:
      - ./all_puntos.sql:/all_puntos.sql
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh

